apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
  - name: amqp
    port: 5672
  - name: management
    port: 15672
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-data-pvc
  labels:
    app: rabbitmq
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8.0-management
        ports:
        - name: amqp
          containerPort: 5672
        - name: management
          containerPort: 15672
        volumeMounts:
          - name: rabbit-data
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbit-data
          persistentVolumeClaim:
            claimName: rabbit-data-pvc
