apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-postgres-config
  labels:
    app: keycloak-postgres
data:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: password
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-postgres
spec:
  serviceName: "keycloak-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
      - name: keycloak-postgres
        image: postgres:12.0-alpine
        envFrom:
          - configMapRef:
              name: keycloak-postgres-config
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: keycloak-postgres-data-pvc
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: keycloak-postgres-data-pvc
    spec:
      storageClassName: rook-ceph-block
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
