apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    app: keycloak
data:
  DB_ADDR: postgres
  DB_PORT: '5432'
  DB_DATABASE: keycloak
  DB_USER: keycloak
  DB_PASSWORD: password
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: nimda
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: NodePort
  ports:
  - name: keycloak
    port: 8080
  - name: keycloak-tls
    port: 8443
    nodePort: 31739
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  serviceName: keycloak
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:8.0.1
        envFrom:
          - configMapRef:
              name: keycloak-config
        ports:
        - name: keycloak
          containerPort: 8080
        - name: keycloak-tls
          containerPort: 8443
        volumeMounts:
          - name: keycloak-tls
            mountPath: "/etc/x509/https"
            readOnly: true
      volumes:
        - name: keycloak-tls
          secret:
            secretName: keycloak-tls
