---
- name: 'Check swarm initialised'
  shell: 'test "$(docker info | grep Swarm | sed ''s/Swarm: //g'')" == "inactive"'
  args:
    executable: /bin/bash
  register: docker_swarm_inactive
  ignore_errors: True

- name: 'Initialise swarm mode'
  when: docker_swarm_inactive.rc == 0
  shell: docker swarm init --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2377

- name: Get the Manager join-token
  shell: docker swarm join-token --quiet manager
  register: manager_token

- name: Get the worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token

- name: Register swarm token facts
  set_fact:
    manager_token: '{{ manager_token }}'
    worker_token: '{{ worker_token }}'
