---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: evelyn-ci
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 9376
      targetPort: 80
      name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: evelyn-ci
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: test
  namespace: evelyn-ci
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: flingflang.evelyn.internal
      http:
        paths:
          - path: ''
            backend:
              serviceName: test
              servicePort: test
---