apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: registry
  namespace: evelyn-ci
spec:
  entryPoints:
  - websecure
  routes:
  - match: HostSNI(`registry.evelyn.internal`)
    services:
    - name: registry
      port: 5000
      terminationDelay: 400
      weight: 10
  tls:
    passthrough: true
