---
- name: Set up the master node
  hosts: master
  remote_user: root
  roles:
    - docker
    - docker-swarm
- name: Set up the slave nodes
  hosts: slave
  remote_user: root
  roles:
    - docker
    - docker-swarm
    - docker-swarm-worker
