---
- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh mode=0777

- name: Check if kubeconfig exists
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: stat_kubelet_conf

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
  when: not stat_kubelet_conf.stat.exists
